name: Build and Deploy Blazor Hosted to Site4Now

on:
  push:
    branches: [ "master" ]

env:
  SERVER_PROJECT_PATH: MyPermutationSolution.Server\MyPermutationSolution.Server.csproj
  PUBLISH_DIR: .\publish

jobs:
  build-and-deploy:
    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        global-json-file: global.json

    - name: Install WebAssembly Tools
      run: dotnet workload install wasm-tools --skip-manifest-update
      
    - name: Clear NuGet cache
      run: dotnet nuget locals all --clear


    - name: Restore dependencies
      run: dotnet restore

    - name: Build
      run: dotnet build --configuration Release --no-restore

    - name: Publish Application
      run: |
        dotnet publish ${{ env.SERVER_PROJECT_PATH }} `
          -c Release `
          -o ${{ env.PUBLISH_DIR }} `
          /p:WebPublishMethod=MSDeploy `
          /p:MSDeployServiceURL="win6145.site4now.net:8172/msdeploy.axd?site=yaiselwong-001-site1" `
          /p:DeployIisAppPath="yaiselwong-001-site1" `
          /p:UserName="yaiselwong-001" `
          /p:Password=${{ secrets.FTP_PASSWORD }} `
          /p:AllowUntrustedCertificate=true `
          /p:UseAppHost=false
